name: fit_track
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  fl_chart: ^1.2.0
  uuid: ^4.6.0
  intl: ^0.20.3
  geolocator: ^14.0.3
  pedometer: ^4.2.0
  permission_handler: 11.4.0
  image_picker: ^1.2.3
  url_launcher: ^6.3.2
  flutter_native_splash: ^2.4.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/

# ==================================================
# FITTRACK APP ICON
# ==================================================

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/fittrack_icon.png"
  adaptive_icon_background: "#0F172A"
  adaptive_icon_foreground: "assets/images/fittrack_icon.png"

# ==================================================
# FITTRACK NATIVE SPLASH
# ==================================================

flutter_native_splash:
  color: "#F8FAFC"

  android: true
  ios: false
  web: false

  android_12:
    color: "#F8FAFC"